### ISSUE TITLE
Eventos passados

### ISSUE THREAD

**Issue by flowck** [meetus/meetus.github.io#1]
Adicionar uma pagina que lista os eventos passados.

**Comment by JoseCage** [comment]
Não sei como ficou esse assunto depois de 3/4 anos @flowck.. Mas a minha sugestão é para edições passadas sejam organizadas por ano, uma vez que o evento é anual (a não ser que num ano se realiza mais de uma vez) ficaria assim `meetus.angodev.com/2015` (ou 2016 por exemplo) e no caso de se realizar 2 ou mais vezes num ano basta colocar o ano e o mês..

**Comment by firminochangani** [comment]
@JoseCage Boas, tal como disseste foi assim que esteve a ser resolvido esta issue. E sim, o próximo ano haverá Meetus. 

CC: @psantos10

**Comment by JoseCage** [comment]
Sobre o próximo ano, vi a atualização no twitter.

Que particularmente espero poder participar, creio que há alguma coisa para partilhar..
